# basic options. I can see whatever I hear. 
title: New Blog Shen 
author: FischinD
email: shenyy1030@gmail.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  yanyan1030

# Build settings
markdown: kramdown
theme: minima
